apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler-service-cronjob
spec:
  schedule: "10 * */2 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10  # Cluster DNS service IP
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"

      backoffLimit: 4
      template:
        metadata:
          labels:
            app: crawler-service
        spec:
          restartPolicy: OnFailure
          containers:
            - name: crawler-service
              image: crawler-service  # Ensure this matches your built image name
              imagePullPolicy: Never
              env:
                - name: KAFKA_SERVER
                  value: "kafka:29092"
                - name: CRAWLER_SERVICE_DB_HOST
                  value: "mysql"
                - name: SCHEMA_REGISTRY_URL
                  value: "http://schema-registry:9091"
